---
paths:
  irf: /fefs/aswg/workspace/marie-sophie.carrasco/projects/analysis/simulation/ressources/size_200_leakage_0.2_gammaness_eff60_ebins_5pdec_diffuse
  gammapy_catalog: /fefs/aswg/workspace/marie-sophie.carrasco/projects/dev-github/gammapy-extra/datasets/catalogs/gammacat/gammacat.fits.gz
  output_dir: ../outputs_dev
  simulated_obs_dir: ../outputs_dev/datasets
  save_name_obs: crab_school
  save_name_suffix: example
data:
  real: True
  save_path_data: ./example_dataset/Crab_Dec_2023
  run_list: [] # None, array of obs_ids
  obs_pattern: dl3_LST-1.Run*.fits
  cos_zenith_bin_edges: [-0.0, 0.25, 0.5, 0.75, 1.0] 
  cos_zenith_bin_centers:  [0.125, 0.375, 0.625, 0.875]
simulation:
  n_run: 2                                    # per wobble
  livetime: 1200                              # [s]
  single_pointing: False                      # If true, only W1 observations are simulated
  obs_collection_type: n_run_obs_per_wobble   # two_wobble_obs, n_run_obs_per_wobble
  t_ref: '2024-10-05 23:00:00'
  delay: 1200                                 # [s]
  time_oversampling: 100                      # [s] time step between subdatasets, i.e. maximum time step for background IRF evaluation
  fov_rotation_error_limit: 1                 # [deg] maximum estimated FoV rotation error before re-evaluation of the background IRF evaluation by gammapy
  e_min: 0.5      # [TeV]
  e_max: 10       # [TeV]
wobble_1:
  run: 11895
  seed: 4
  obs_id: '1'
wobble_2:
  run: 11896
  seed: 42
  obs_id: '2'
source:
  catalog_name: Crab nebula # Gammacat name. If not found, will use coordinates given in config
  coordinates:
    ra: 83.63308
    dec: 22.0145
  flux_to_0: False # Set to True for background only simulated data
  exclusion_region:
    shape: n_circles # n_circles, ellipse, noexclusion
    n_circles:
      circle_1:                               # Crab
        radius: 0.35
        ra: 83.63308
        dec: 22.0145
      circle_2:                               # Zeta tauri      
        radius: 0.35
        ra: 84.4125
        dec: 21.1425
    ellipse:
      width: 0.2                              # [°]
      height: 0.6                             # [°]
      angle: 45                               # [°]
background:
  spectral_model:
    model: PowerLawNormSpectralModel
    factor: 2.4
    scale: 1
    norm: 10
    reference: 1 TeV
    unit: sr-1 s-1 TeV-1
  spatial_model:
    model: GaussianSpatialModel_LinearGradient
    lon_0: 0
    lat_0: 0
    lon_grad: 0
    lat_grad: 0
    lon_grad_variation: False
    lat_grad_variation: False
    sigma: 0.6
    phi: 0
    e: 0
    unit: "deg"
  maker:
    correlation_radius: 0.08    # [deg]
    correlate_off: True
    ring:
      internal_ring_radius: 0.2 # [deg]
      width: 0.3                # [deg]
    fov:
      method: scale # scale, fit
irf:
  dimension: 3
  collection: False
  FoV_alignment: ALTAZ # ALTAZ, RADEC
  down_factor: 10
  offset_factor: 2
dataset:
  width_factor: 2.5
  binsize: 0.02               # [deg]
acceptance:
  method: stack # stack,fit
  collection: True
  single_file_path: /fefs/aswg/workspace/ali.baktash/simulation_data/centered_full_gaussian/no_exlcusion/teststacked_exclusion_map.fits
  energy:
    e_min: 0.1
    e_max: 40
    unit: TeV
    nbin: 3
  offset:
    offset_max: 2.5           # [deg]
    nbin: 11
  cos_zenith_binning:
    zenith_binning: False
    initial_cos_zenith_binning: 0.01
    runwise_normalisation: False
    cos_zenith_binning_method: min_livetime_per_wobble
    cos_zenith_binning_parameter_value: 3000    # [s] if 'livetime' in method
  fit:
    fnc: bilinear_gaussian2d
    bounds:
      x_cm: [-5,5]
      y_cm: [-5,5]
      # psi: [0,0]
      #width: [0.3,0.33]
      #length: [0.3,0.33]
      #x_gradient: [-11,-9.99] 
      #y_gradient: [0,0] 
