---
paths:
  path_data: ./crab_LZA_data
  models: ./SimBMVtool/models.yaml
  gammapy_catalog: ./gammapy-extra/datasets/catalogs/gammacat/gammacat.fits.gz
  output_dir: ./outputs
  subdir: crab_LZA
data:
  run_list: [] # None, array of obs_ids
  obs_pattern: dl3_*
  cos_zenith_bin_edges: [-0.0, 0.25, 0.5, 0.75, 1.0] 
  cos_zenith_bin_centers:  [0.125, 0.375, 0.625, 0.875]
source:
  catalog_name: Crab # Gammacat name. If not found, will use coordinates given in config
  coordinates:
    ra: 83.63308
    dec: 22.0145
  exclusion_region:
    shape: n_shapes # n_shapes, noexclusion
    regions:
      circle_1:                               # Crab
        radius: 0.1
        ra: 83.63308
        dec: 22.0145
        is_source: True
      # circle_2:                               # Zeta tauri, commented for tutorial purpose  
      #   radius: 0.4
      #   ra: 84.4125
      #   dec: 21.1425
      #   is_source: False
background:
  maker:
    correlation_radius: 0.08    # [deg]
    correlate_off: True
    ring:
      internal_ring_radius: 0.1 # [deg]
      width: 0.35                # [deg]
    fov:
      method: fit # scale, fit
acceptance:
  dimension: 3
  tool: baccmod
  method: stack # stack,fit
  out_collection: True # False if same output IRF for all runs, like with pybkgmodel
  FoV_alignment: ALTAZ # ALTAZ, RADEC
  fov_rotation_error_limit: 1                 # [deg] maximum estimated FoV rotation error before re-evaluation of the background IRF evaluation by gammapy
  energy:
    e_min: 0.2
    e_max: 40
    unit: TeV
    nbin: 3
  offset:
    offset_max: 2.5           # [deg]
    nbin: 11
  cos_zenith_binning:
    zenith_binning: False
    zenith_interpolation: True
    zenith_binning_run_splitting: True
    initial_cos_zenith_binning: 0.01
    runwise_normalisation: False
    cos_zenith_binning_method: min_livetime_per_wobble
    cos_zenith_binning_parameter_value: 3000    # [s] if 'livetime' in method, n_obs if 'observation' in method
  fit:
    fnc: bilinear_gaussian2d
    bounds:
      x_cm: [-5,5]
      y_cm: [-5,5]
      # psi: [0,0]
      #width: [0.3,0.33]
      #length: [0.3,0.33]
      #x_gradient: [-11,-9.99] 
      #y_gradient: [0,0] 
