---
paths:
  path_data: <path_to_dl3>
  gammapy_catalog: <path_to_local_gammapy_data_copy>/catalogs/gammacat/gammacat.fits.gz 
  output_dir: ../outputs
  subdir: crab_school
data:
  run_list: [] # None, array of obs_ids
  obs_pattern: dl3_*
  cos_zenith_bin_edges: [-0.0, 0.25, 0.5, 0.75, 1.0] 
  cos_zenith_bin_centers:  [0.125, 0.375, 0.625, 0.875]
source:
  catalog_name: Crab Nebula # Gammacat name. If not found, will use coordinates given in config
  coordinates:
    ra: 83.63308
    dec: 22.0145
  exclusion_region:
    shape: n_circles # n_circles, ellipse, noexclusion
    n_circles:
      circle_1:                               # Crab
        radius: 0.3
        ra: 83.63308
        dec: 22.0145
      # circle_2:                               # Zeta tauri, commented for tutorial purpose  
      #   radius: 0.35
      #   ra: 84.4125
      #   dec: 21.1425
background:
  maker:
    correlation_radius: 0.08    # [deg]
    correlate_off: True
    ring:
      internal_ring_radius: 0.2 # [deg]
      width: 0.3                # [deg]
    fov:
      method: scale # scale, fit
acceptance:
  dimension: 3
  tool: baccmod
  method: stack # stack,fit
  out_collection: True
  FoV_alignment: ALTAZ # ALTAZ, RADEC
  energy:
    e_min: 0.1
    e_max: 40
    unit: TeV
    nbin: 3
  offset:
    offset_max: 2.5           # [deg]
    nbin: 11
  cos_zenith_binning:
    zenith_binning: False
    initial_cos_zenith_binning: 0.01
    runwise_normalisation: False
    cos_zenith_binning_method: min_livetime_per_wobble
    cos_zenith_binning_parameter_value: 3000    # [s] if 'livetime' in method, n_obs if 'observation' in method
  fit:
    fnc: bilinear_gaussian2d
    bounds:
      x_cm: [-5,5]
      y_cm: [-5,5]
      # psi: [0,0]
      #width: [0.3,0.33]
      #length: [0.3,0.33]
      #x_gradient: [-11,-9.99] 
      #y_gradient: [0,0] 
